# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4009579fa337c0324c8fa3dfd5b99923debd6f7727a6b5bc5bb1119496b79963df3284bc80d50284c4daa0725bb2ea58c76c4c051e6179cd5b41c91436f71e48

test:
  secret_key_base: f48e24f6493c9f73ecdcd0d99d32054c5f461317defb0917517854a088c4e13f36bf3b6db54ba6f93ca4bd607f2e43d90a797729a61abf45a8e145f9c45f99e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
